name: build ruby
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ruby/**
jobs:
  push:
    name: "yolks:ruby_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 3.2.2
    steps:
      - uses: actions/checkout@v3
      # Setup QEMU for ARM64 Build
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: ./ruby
          file: ./ruby/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/csaller/yolks:ruby_${{ matrix.tag }}
          build-args: |
            RUBY_VERSION=${{ matrix.tag }}
